# Generated by Django 4.2.4 on 2024-04-18 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_machine_productionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionlog',
            name='end_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='productionlog',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
